### ISSUE TITLE
Create second docker image for cs251?

### ISSUE THREAD

**Issue by maxnz** [StoDevX/stograde#131]
I have found that the -fPIC issue from #118 is still a problem when using the cs251tk image.
Doing some testing, I have found that using the `gcc:latest` image as the base image and manually installing python3 dev tools fixes this.
@hawkrives @rye would it be possible to create a second docker image for each release, named something like `cs251tk:version-gcc` and `cs251tk:latest-gcc`, that could be used for cs251?

The Dockerfile might look like this:
```
# Use the base Python 3.6 image.  It is sufficient for accomplishing
# most of the stuff, and includes some handy build tools like gcc.
#
# NOTE This could be changed to something like `python:latest` if we
# find that there is no dependency on 3.6 itself.
FROM gcc:latest

# Set the MAINTAINER flag of the docker image.
#
# NOTE Consider changing this or removing it; it is not necessary
# unless pushing to Docker Hub.
MAINTAINER Kristofer Rye <kristofer.rye@gmail.com>

# Add the entire project directory to the /cs251tk/ directory in the
# image.
ADD . /cs251tk/

# Create the SSH config directory on the root user account home directory.
RUN mkdir -p /root/.ssh/

# Build a smart SSH config (and prepare to use our id_rsa from the host)
RUN echo "Host *.stolaf.edu\n\tUserKnownHostsFile /dev/null\n\tStrictHostKeyChecking no\n\tIdentityFile /root/.ssh/id_rsa" >> /root/.ssh/config

# Lock down our SSH config
RUN chmod 600 /root/.ssh/config

# Add a marked dependency volume folder.
VOLUME /cs251tk_share/

# Change into our project directory.
WORKDIR /cs251tk

# Make a symlink between /cs251tk_share/blah and /cs251tk/blah
RUN ln -sv /cs251tk_share/data /cs251tk/data
RUN ln -sv /cs251tk_share/students /cs251tk/students
RUN ln -sv /cs251tk_share/logs /cs251tk/logs
RUN ln -sv /cs251tk_share/students.txt /cs251tk/students.txt

# Make symlinks for our SSH keys.
RUN ln -sv /cs251tk_share/.ssh/id_rsa /root/.ssh/id_rsa
RUN ln -sv /cs251tk_share/.ssh/id_rsa.pub /root/.ssh/id_rsa.pub

# Update the package cache.
RUN apt-get update

# TODO Install any additional requirements.  Do we have any?
RUN apt-get install -y python3-setuptools python3-dev python3-pip

# Install the toolkit from the source directory.
RUN pip3 install .

# Print out the versions of the installed tools.
RUN gcc --version \
    && g++ --version \
    && make --version \
    && git --version \
    && python --version

# Finally, set our default command to just "cs251tk".
CMD ["cs251tk"]
```

**Comment by rye** [comment]
Just for everyone's information, `-fPIC` generates position-independent code, for linking into shared libraries specifically. gcc may be giving you a false hint to use `-fPIC` because it notices a disparity between the symbols it's trying to link against and the symbols referenced by the `.o` files, which can often happen if operating across different versions of `glibc` or `gcc` itself. Since this container is originally based on `3-slim` which uses Debian's slim variant, it's possible that students committed their `.o` files, which were compiled against a different libc such as on the link machines? Could this be the case, @maxnz? FYI, I have no insight into the architecture here beyond PR descriptions into what changes are being made.

I personally would prefer a worker model where the builds are occurring in their own individual containers, but I imagine that is a bit beyond the requirement to fix the issue you're seeing. I'd be open to making another variant, and I'm happy to do that if all that is needed is to change the base and manually install stuff.

**Comment by maxnz** [comment]
All the .o files are pre-compiled by professor Olaf so none of the students have actually even seen the source code behind them. I asked him to recompile them with the -fPIC flag and that didn't seem to make a difference.

**Comment by rye** [comment]
Yes, I imagine the .o files are compiled against a different libc because they are being compiled by Olaf in his environment, not the glibc we have in our container image, unless the two are the same.

**Comment by hawkrives** [comment]
I have no particular objection to making a second image… but I wish they'd quit distributing only the object files. (The professors not distributing the source code to things has long been a pet peeve of mine.)

**Comment by hawkrives** [comment]
@maxnz Do you think we still need this?

**Comment by maxnz** [comment]
Probably, but I'm not sure yet. We can check once students start submitting work within the next week by getting a couple of testers to try removing the --skip-web-compile flag that temporarily bypasses this issue.
